// GENERATED from loadouts.md. Do not edit this file directly — edit
// loadouts.md at the repo root and ask Claude to regenerate this file.
// See loadouts.md "Instructions for Claude" for the protocol.

import { modules, comingSoonModules, type Module, type ComingSoonModule } from "./modules";

export interface LoadoutModule {
  // Slug from modules.ts or comingSoonModules. The page resolves this to the
  // full module record at render time so name/description/products stay in
  // sync with the source of truth.
  //
  // When this entry is a "pick one of" group (e.g. the e-collar holster —
  // the trainer should pick whichever fits their receiver), `slug` is
  // omitted and the entry uses `choices` instead.
  slug?: string;
  // STL filename (relative to site/public/models/) of the plate or belt-clip
  // variant this module bolts to *in this loadout*. Optional because some
  // modules (e.g. the BioThane heel lead, `noModel: true`) don't bolt to
  // anything — they're hung from the belt or worn as a separate accessory.
  plate?: string;
  // Optional variant id (matches a `VariantOption.id` under
  // `module.genericVariants`). Used when a module ships in multiple sizes
  // and the loadout needs a specific one (e.g. carabiner-clip → "small").
  //
  // Can also be an array of variant ids — in which case the entry
  // represents *multiple instances* of the same module sharing one plate
  // (e.g. two carabiner-clips, one "tiny" and one "small", bolted to a
  // single 2×3 plate). The module-list row shows each variant as a
  // sub-bullet; the print list still counts the plate once but adds each
  // variant's STL.
  variant?: string | string[];
  // Optional one-line note explaining why this module is in this loadout.
  note?: string;
  // "Pick one of" group. When set, this entry doesn't reference a single
  // module — it lists candidate module slugs the user picks among. The
  // page renders a single combined card (with `groupLabel`) and links to
  // each candidate; the print list and products section group all
  // candidates under a single "pick one of" header.
  choices?: string[];
  // Display name for the group card (e.g. "E-Collar Holster"). Required
  // when `choices` is set.
  groupLabel?: string;
  // One-paragraph description shown on the group card.
  groupDescription?: string;
}

export interface Loadout {
  slug: string;
  name: string;
  tagline: string;
  description: string;
  belt: '1.5"' | '2"';
  beltNote: string;
  // The specific belt product this loadout recommends. Surfaces at the top
  // of the "Products for this loadout" section with a required chip.
  // Optional: Freeform uses belt clips on a regular pants belt — no
  // specific duty belt to recommend.
  beltProduct?: { name: string; url: string };
  modules: LoadoutModule[];
}

export const loadouts: Loadout[] = [
  {
    slug: "trainer",
    name: "The Trainer",
    tagline: "Built for people who work with dogs all day.",
    description:
      "A working setup for professional and amateur trainers, laid out for a 2\" MOLLE duty belt. Clockwise from the top: clicker, treat bag, e-collar, MK3 spray, waste bags, flashlight, dump bag, heel lead, and a carabiner. Everything is exactly where your hand expects it.",
    belt: '2"',
    beltNote:
      "Built around the IDOGEAR SPORTS 2\" MOLLE duty belt. The extra MOLLE webbing carries the non-Kanix gear (water, radio) that doesn't bolt to a plate.",
    beltProduct: {
      name: 'IDOGEAR SPORTS Tactical 2" Heavy-Duty MOLLE Belt',
      url: "https://www.amazon.com/dp/B0G2PTBGF2",
    },
    modules: [
      { slug: "clicker-holder", plate: "plates/kanix_plate_3x3_52x12.stl", note: "Clicker rides on the 12mm plate behind the buckle where the belt doubles over." },
      { slug: "treat-bag-mount", plate: "plates/kanix_plate_3x3_52x6.5.stl", note: "Wilderdog treat bag on your dominant-hand side — fastest possible reinforcement." },
      {
        groupLabel: "E-Collar Holster",
        groupDescription:
          "Pick the holster that matches the e-collar receiver you already own. All e-collar holsters use the same 3×3 / 52mm / 6.5mm plate, so the mount is identical no matter which one you print.",
        choices: ["mini-educator-holder", "dogtra-200ncpt-202c-arc-holder", "dogtra-280x-arcx-holder"],
        plate: "plates/kanix_plate_3x3_52x6.5.stl",
        note: "Click any of the candidates to see which e-collars it supports.",
      },
      { slug: "mk3-canister-holder", plate: "plates/kanix_plate_3x3_52x6.5.stl", note: "Off-leash dog approach — the most likely emergency on a session." },
      { slug: "waste-bag-dispenser", plate: "plates/kanix_plate_3x3_52x6.5.stl" },
      { slug: "flashlight-holster-c3", plate: "plates/kanix_plate_3x3_52x6.5.stl", note: "Wuben C3 — early-morning and late-evening sessions." },
      { slug: "dump-bag-mount", plate: "plates/kanix_plate_3x3_52x6.5.stl", note: "Catch-all storage — backup leashes, wipes, extras you pick up on a session." },
      { slug: "quick-detach-biothane-heel-lead", note: "BioThane heel lead. Loops directly around the belt — no plate." },
      { slug: "carabiner-clip", plate: "plates/kanix_plate_2x3_52x6.5.stl", variant: ["tiny", "small"], note: "Two 1×2 carabiner clips share one plate — a tiny clip and a small clip stacked. Clip on a second leash, keys, or a water bottle without burning a full module slot." },
    ],
  },
  {
    slug: "walker",
    name: "The Walker",
    tagline: "Hands-free for the daily neighborhood loop.",
    description:
      "The minimal everyday carry: waste bags, treats, and a flashlight for early or late walks. No bulk, no extras — just what you reach for on every walk.",
    belt: '1.5"',
    beltNote:
      "A 1.5\" duty belt is plenty for a light loadout and tucks under everyday clothing better than a 2\" belt.",
    beltProduct: {
      name: "IDOGEAR SPORTS Tactical Ratchet Belt (1.5\")",
      url: "https://www.amazon.com/dp/B0FJDMN78R",
    },
    modules: [
      { slug: "waste-bag-dispenser", plate: "plates/kanix_plate_2x2_38x5.3.stl" },
      { slug: "treat-bag-mount", plate: "plates/kanix_plate_2x2_38x5.3.stl", note: "A small reward stash for everyday training opportunities." },
      { slug: "flashlight-holster-g5", plate: "plates/kanix_plate_2x2_38x5.3.stl", note: "Compact EDC light for the dark side of the daily loop." },
      { slug: "carabiner-clip", plate: "plates/kanix_plate_2x2_38x5.3.stl", note: "Clip keys or a phone tether so they're not in your pocket." },
    ],
  },
  {
    slug: "hiker",
    name: "The Hiker",
    tagline: "Configured for trails, long days, and the unexpected.",
    description:
      "Built for full-day outings where you might be hours from a vehicle. Carries everything from a backup leash to a first aid kit, plus options for terrain hazards (other dogs, wildlife, dim light). The dump pouch handles whatever you pick up on the trail — extra layers, gloves, a packed-out poop bag — so it isn't living in your hand.",
    belt: '2"',
    beltNote:
      "A 2\" duty belt distributes weight better on long days and keeps the loadout from bouncing on technical terrain.",
    beltProduct: {
      name: 'IDOGEAR SPORTS Tactical 2" Heavy-Duty MOLLE Belt',
      url: "https://www.amazon.com/dp/B0G2PTBGF2",
    },
    modules: [
      { slug: "first-aid-kit-mount", plate: "plates/kanix_plate_3x3_52x6.5.stl", note: "Hours from a trailhead — first aid is non-negotiable." },
      { slug: "waste-bag-dispenser", plate: "plates/kanix_plate_3x3_52x6.5.stl" },
      { slug: "slip-lead-wrap-post", plate: "plates/kanix_plate_3x3_52x6.5.stl", note: "Backup leash in case the primary fails on the trail." },
      { slug: "dump-bag-mount", plate: "plates/kanix_plate_3x3_52x6.5.stl", note: "Stash a packed-out bag, gloves, a layer, or extras you pick up on the trail." },
      { slug: "mk3-canister-holder", plate: "plates/kanix_plate_3x3_52x6.5.stl", note: "Off-leash dog encounters are most likely on shared trails." },
      { slug: "flashlight-holster-c3", plate: "plates/kanix_plate_3x3_52x6.5.stl", note: "Dawn starts and dusk returns — bring real light." },
      { slug: "carabiner-clip", plate: "plates/kanix_plate_3x3_52x6.5.stl", note: "Tether keys, a multitool, or a second leash." },
    ],
  },
  {
    slug: "freeform",
    name: "The Freeform",
    tagline: "Mix and match — build the belt that fits how you actually work.",
    description:
      "There's no single \"right\" Kanix™ setup. The Freeform is the open invitation: pick the modules you actually reach for, arrange them where your hands expect them, and skip the rest. This is a starting point for handlers whose workflow doesn't match the Trainer, Walker, or Hiker profiles — multi-dog handlers, kennel staff, sport competitors, anyone whose gear list is their own.",
    belt: '1.5"',
    beltNote:
      "Built around the Kanix™ belt clip adapter — no duty belt required. Clip each module onto a regular pants belt; mix grid sizes as needed.",
    modules: [
      { slug: "waste-bag-dispenser", plate: "belt_clip_2x2_38mm.stl" },
      { slug: "treat-bag-mount", plate: "belt_clip_3x2_38mm.stl", note: "Always-useful, regardless of workflow." },
      { slug: "clicker-holder", plate: "belt_clip_2x2_38mm.stl", note: "Add if you're doing any marker-based training." },
      { slug: "slip-lead-wrap-post", plate: "belt_clip_2x2_38mm.stl", note: "Backup leash that fits any handler's worst-case." },
      { slug: "flashlight-holster-c3", plate: "belt_clip_3x3_38mm.stl", note: "Pick C3 (or swap to G5 below) based on how much throw you want." },
      { slug: "carabiner-clip", plate: "belt_clip_3x3_38mm.stl", note: "Multipurpose: keys, second leash, water bottle clip." },
      { slug: "dump-bag-mount", plate: "belt_clip_3x3_38mm.stl", note: "Catch-all storage for whatever you end up carrying on a given day." },
    ],
  },
];

// One resolved entry. Either a single module (kind === "module" |
// "coming-soon") or a "pick one of" group of modules (kind === "group").
export type ResolvedLoadoutModule =
  | {
      kind: "module" | "coming-soon";
      module: Module | ComingSoonModule;
      plate?: string;
      variant?: string | string[];
      note?: string;
    }
  | {
      kind: "group";
      groupLabel: string;
      groupDescription?: string;
      // Each candidate the user picks among. `mod` is the module record;
      // `kind` distinguishes shipping vs coming-soon for the page link.
      candidates: Array<{ kind: "module" | "coming-soon"; module: Module | ComingSoonModule }>;
      plate?: string;
      note?: string;
    };

// Helper: resolve each entry. For a normal entry, look up the slug in
// modules (then comingSoonModules). For a "pick one of" group, resolve
// every candidate slug. Logs a warning if any slug doesn't resolve.
export function resolveLoadout(loadout: Loadout): ResolvedLoadoutModule[] {
  return loadout.modules
    .map((entry): ResolvedLoadoutModule | null => {
      if (entry.choices && entry.choices.length > 0) {
        const candidates = entry.choices
          .map((slug) => {
            const mod = modules.find((m) => m.slug === slug);
            if (mod) return { kind: "module" as const, module: mod };
            const cs = comingSoonModules.find((m) => m.slug === slug);
            if (cs) return { kind: "coming-soon" as const, module: cs };
            console.warn(
              `[loadouts] loadout "${loadout.slug}" group references unknown slug "${slug}"`,
            );
            return null;
          })
          .filter((x): x is { kind: "module" | "coming-soon"; module: Module | ComingSoonModule } => x !== null);
        if (candidates.length === 0) return null;
        return {
          kind: "group",
          groupLabel: entry.groupLabel ?? "Pick one",
          groupDescription: entry.groupDescription,
          candidates,
          plate: entry.plate,
          note: entry.note,
        };
      }
      if (!entry.slug) return null;
      const mod = modules.find((m) => m.slug === entry.slug);
      if (mod) {
        return { kind: "module", module: mod, plate: entry.plate, variant: entry.variant, note: entry.note };
      }
      const cs = comingSoonModules.find((m) => m.slug === entry.slug);
      if (cs) {
        return { kind: "coming-soon", module: cs, plate: entry.plate, variant: entry.variant, note: entry.note };
      }
      console.warn(
        `[loadouts] loadout "${loadout.slug}" references unknown module slug "${entry.slug}"`,
      );
      return null;
    })
    .filter((x): x is ResolvedLoadoutModule => x !== null);
}

// One row in the loadout's print list. `kind` tells the page how to label
// it ("Mount" — the plate or belt clip everything bolts to — vs "Module"
// — the accessory itself); `stl` is the path under public/models/.
export interface LoadoutPrintItem {
  kind: "mount" | "module";
  stl: string;
  count: number;
  label: string;
}

// Helper: collect everything the user needs to print for this loadout —
// the unique mounts (plates or belt clips) AND each module's default STL.
// Modules with `noModel: true` (e.g. the BioThane heel lead) are skipped.
// Mounts come first so they print before the accessories that bolt to them.
export function summarizeLoadoutPrintList(loadout: Loadout): LoadoutPrintItem[] {
  // Mounts first. Skip entries with no plate (e.g. the BioThane heel lead —
  // it loops around the belt on its own). "Pick one of" group entries
  // still contribute their plate (the user prints one mount even if they
  // pick one of N holsters).
  const mountCounts = new Map<string, number>();
  for (const entry of loadout.modules) {
    if (!entry.plate) continue;
    mountCounts.set(entry.plate, (mountCounts.get(entry.plate) ?? 0) + 1);
  }
  const mounts: LoadoutPrintItem[] = [...mountCounts.entries()].map(
    ([stl, count]) => ({
      kind: "mount",
      stl,
      count,
      label: plateLabel(stl),
    }),
  );

  // Modules next. For modules with `genericVariants`, use the variant id
  // from the loadout entry to look up the correct STL/label; otherwise use
  // the module's default `stlFile`. Skip modules that don't have a model
  // (noModel) or that aren't in the printable modules list (coming-soon).
  // Skip "pick one of" groups — the user prints one of them, but we don't
  // know which, so the group surfaces in the products section instead.
  // Multi-variant entries (`variant: string[]`) add one STL per variant.
  const moduleCounts = new Map<string, { count: number; name: string }>();
  const addModuleSTL = (stl: string, label: string) => {
    const existing = moduleCounts.get(stl);
    moduleCounts.set(
      stl,
      existing
        ? { count: existing.count + 1, name: label }
        : { count: 1, name: label },
    );
  };
  for (const entry of loadout.modules) {
    if (entry.choices) continue;
    const mod = modules.find((m) => m.slug === entry.slug);
    if (!mod || mod.noModel) continue;

    const variantIds: Array<string | undefined> = Array.isArray(entry.variant)
      ? entry.variant
      : [entry.variant];

    for (const vid of variantIds) {
      let stl: string | undefined;
      let label: string = mod.name;
      if (vid && mod.genericVariants) {
        const opt = mod.genericVariants.groups
          .flatMap((g) => g.options)
          .find((o) => o.id === vid);
        if (opt) {
          stl = opt.stlFile;
          label = `${mod.name} — ${opt.label}${opt.sublabel ? ` (${opt.sublabel})` : ""}`;
        }
      }
      if (!stl) stl = mod.stlFile;
      if (!stl) continue;
      addModuleSTL(stl, label);
    }
  }
  const modulesList: LoadoutPrintItem[] = [...moduleCounts.entries()].map(
    ([stl, { count, name }]) => ({
      kind: "module",
      stl,
      count,
      label: name,
    }),
  );

  return [...mounts, ...modulesList];
}

// Helper: total M5×10 button-head cap screws a loadout needs across all
// of its modules. Modules without a declared `screwCount` are skipped
// (treated as unknown, not zero). For "pick one of" groups, take the
// max screw count across candidates so the user has enough no matter
// which they pick.
export function totalLoadoutScrews(loadout: Loadout): number {
  let total = 0;
  for (const entry of loadout.modules) {
    if (entry.choices && entry.choices.length > 0) {
      let groupMax = 0;
      for (const slug of entry.choices) {
        const mod =
          modules.find((m) => m.slug === slug) ??
          comingSoonModules.find((m) => m.slug === slug);
        if (mod && typeof mod.screwCount === "number") {
          groupMax = Math.max(groupMax, mod.screwCount);
        }
      }
      total += groupMax;
      continue;
    }
    if (!entry.slug) continue;
    const mod =
      modules.find((m) => m.slug === entry.slug) ??
      comingSoonModules.find((m) => m.slug === entry.slug);
    if (mod && typeof mod.screwCount === "number") {
      // Multi-variant entries (e.g. two carabiner clips on one plate) need
      // screws for each clip — multiply by the variant count.
      const multiplier = Array.isArray(entry.variant) ? entry.variant.length : 1;
      total += mod.screwCount * multiplier;
    }
  }
  return total;
}

// One row in the "Products for this loadout" section. `source` is either
// the loadout itself (for the belt) or the slug of the module the product
// belongs to (so the page can link back). `required` is true if the
// product is mandatory to use the loadout (the belt is always required;
// a module's `required: true` product is also required); otherwise the
// product is just a suggestion. `pickOneGroup` is set when the product
// belongs to a "pick one of" cluster (e.g. e-collar receivers) — the
// page draws a heading and groups all rows with the same value.
export interface LoadoutProductRow {
  name: string;
  url: string;
  required: boolean;
  source: { kind: "belt" } | { kind: "module"; slug: string; moduleName: string };
  pickOneGroup?: string;
}

// Helper: collect every product the user might want to buy for this
// loadout. The belt is first (if specified), then every module's products
// in module-list order. "Pick one of" group entries surface every
// candidate module's products with the same `pickOneGroup` tag so the
// page can render them as a single cluster.
export function collectLoadoutProducts(loadout: Loadout): LoadoutProductRow[] {
  const rows: LoadoutProductRow[] = [];

  if (loadout.beltProduct) {
    rows.push({
      name: loadout.beltProduct.name,
      url: loadout.beltProduct.url,
      required: true,
      source: { kind: "belt" },
    });
  }

  for (const entry of loadout.modules) {
    if (entry.choices && entry.choices.length > 0) {
      const groupLabel = entry.groupLabel ?? "Pick one";
      for (const slug of entry.choices) {
        const mod =
          modules.find((m) => m.slug === slug) ??
          comingSoonModules.find((m) => m.slug === slug);
        if (!mod || !mod.products) continue;
        for (const p of mod.products) {
          rows.push({
            name: p.name,
            url: p.url,
            // Products inside a pick-one cluster are "pick one of" — none
            // is individually required (the cluster as a whole is). We
            // mark them as not required individually; the page renders a
            // group header noting one must be chosen.
            required: false,
            source: { kind: "module", slug: mod.slug, moduleName: mod.name },
            pickOneGroup: groupLabel,
          });
        }
      }
      continue;
    }
    const mod =
      modules.find((m) => m.slug === entry.slug) ??
      comingSoonModules.find((m) => m.slug === entry.slug);
    if (!mod || !mod.products) continue;
    for (const p of mod.products) {
      rows.push({
        name: p.name,
        url: p.url,
        required: p.required === true,
        source: { kind: "module", slug: mod.slug, moduleName: mod.name },
      });
    }
  }

  return rows;
}

// Parse the STL filename into a human label. Filenames follow two patterns
// that the rest of the codebase already establishes:
//   - "plates/kanix_plate_<grid>_<belt>x<thickness>.stl"
//   - "belt_clip_<grid>_<belt>mm.stl"
// Anything that doesn't match falls through to a sensible default so a typo
// in loadouts.md doesn't crash the page — but the value will read wrong, so
// the user notices.
export function plateLabel(plate: string | undefined | null): string {
  if (!plate) return "(no plate specified)";
  const plateMatch = plate.match(/kanix_plate_(\d+x\d+)_(\d+)x([\d.]+)\.stl$/);
  if (plateMatch) {
    const [, grid, belt, thickness] = plateMatch;
    return `Kanix™ Plate — ${grid} grid, ${belt}mm belt, ${thickness}mm thick`;
  }
  const clipMatch = plate.match(/belt_clip_(\d+x\d+)_(\d+)mm\.stl$/);
  if (clipMatch) {
    const [, grid, belt] = clipMatch;
    return `Belt Clip — ${grid} grid, ${belt}mm belt`;
  }
  return plate;
}
