// GENERATED from loadouts.md. Do not edit this file directly — edit
// loadouts.md at the repo root and ask Claude to regenerate this file.
// See loadouts.md "Instructions for Claude" for the protocol.

import { modules, comingSoonModules, type Module, type ComingSoonModule } from "./modules";

export interface LoadoutModule {
  // Slug from modules.ts or comingSoonModules. The page resolves this to the
  // full module record at render time so name/description/products stay in
  // sync with the source of truth.
  //
  // When this entry is a "pick one of" group (e.g. the e-collar holster —
  // the trainer should pick whichever fits their receiver), `slug` is
  // omitted and the entry uses `choices` instead.
  slug?: string;
  // STL filename (relative to site/public/models/) of the plate or belt-clip
  // variant this module bolts to *in this loadout*. Optional because some
  // modules (e.g. the BioThane heel lead, `noModel: true`) don't bolt to
  // anything — they're hung from the belt or worn as a separate accessory.
  plate?: string;
  // Optional variant id (matches a `VariantOption.id` under
  // `module.genericVariants`). Used when a module ships in multiple sizes
  // and the loadout needs a specific one (e.g. carabiner-clip → "small").
  //
  // Can also be an array of variant ids — in which case the entry
  // represents *multiple instances* of the same module sharing one plate
  // (e.g. two carabiner-clips, one "tiny" and one "small", bolted to a
  // single 2×3 plate). The module-list row shows each variant as a
  // sub-bullet; the print list still counts the plate once but adds each
  // variant's STL.
  variant?: string | string[];
  // Optional one-line note explaining why this module is in this loadout.
  note?: string;
  // "Pick one of" group. When set, this entry doesn't reference a single
  // module — it lists candidate module slugs the user picks among. The
  // page renders a single combined card (with `groupLabel`) and links to
  // each candidate; the print list and products section group all
  // candidates under a single "pick one of" header.
  choices?: string[];
  // Display name for the group card (e.g. "E-Collar Holster"). Required
  // when `choices` is set.
  groupLabel?: string;
  // One-paragraph description shown on the group card.
  groupDescription?: string;
  // Position on the belt for the top-down "belt layout" visualization.
  // Degrees clockwise from the buckle (front center) as seen from above the
  // wearer: 0 = front center, +90 = right hip, -90 (or 270) = left hip,
  // 180 = small of back. Entries without an angle are omitted from the
  // visualization (e.g. the BioThane heel lead, which loops around the
  // belt without a fixed position).
  angle?: number;
}

export interface Loadout {
  slug: string;
  name: string;
  tagline: string;
  description: string;
  belt: '1.5"' | '2"';
  beltNote: string;
  // The specific belt product this loadout recommends. Surfaces at the top
  // of the "Products for this loadout" section with a required chip.
  // Optional: Freeform uses belt clips on a regular pants belt — no
  // specific duty belt to recommend.
  beltProduct?: { name: string; url: string; costCents?: number };
  modules: LoadoutModule[];
}

export const loadouts: Loadout[] = [
  {
    slug: "walker",
    name: "The Walker",
    tagline: "Hands-free for the daily neighborhood loop.",
    description:
      "Three Kanix™ modules on a 1.5\" duty belt plus a hands-free BioThane heel lead — the lead loops straight onto the belt so you never have to hold a leash on the daily loop. Wuben C3 flashlight stacks with a tiny attachment loop on one module, waste bags on another, two more attachment loops share the third. Light enough to disappear under everyday clothing.",
    belt: '1.5"',
    beltNote:
      "A 1.5\" duty belt is plenty for a light loadout and tucks under everyday clothing better than a 2\" belt.",
    beltProduct: {
      name: "IDOGEAR SPORTS Tactical Ratchet Belt (1.5\")",
      url: "https://www.amazon.com/dp/B0FJDMN78R",
      costCents: 2500,
    },
    modules: [
      { slug: "flashlight-holster-c3", plate: "plates/kanix_plate_3x2_38x5.3.stl", variant: "38mm", angle: 60, note: "Wuben C3 (38mm 2×2 variant) shares its 3×2 plate with a tiny attachment loop for clipping keys or a phone tether." },
      { slug: "carabiner-clip", plate: "plates/kanix_plate_3x2_38x5.3.stl", variant: "tiny", angle: 60, note: "Tiny attachment loop stacked on the C3's plate — clip your own carabiner, snap hook, or D-clip to it." },
      { slug: "quick-detach-biothane-heel-lead", note: "BioThane lead, used here as a slip lead. Loops directly around the belt — no plate." },
      { slug: "waste-bag-dispenser", plate: "plates/kanix_plate_3x2_38x5.3.stl", angle: -45 },
      { slug: "carabiner-clip", plate: "plates/kanix_plate_3x2_38x5.3.stl", variant: ["small", "small"], angle: 20, note: "Two of the larger 1×2 attachment loops on one 3×2 plate — clip a second leash, water bottle, or anything that needs more than a tiny loop." },
    ],
  },
  {
    slug: "hiker",
    name: "The Hiker",
    tagline: "Configured for trails, long days, and the unexpected.",
    description:
      "Five Kanix™ modules on a 2\" MOLLE belt for full-day outings where you might be hours from a vehicle: first aid kit, MK3 spray for off-leash encounters, Wuben C3 flashlight for dawn-and-dusk legs, waste bags, and an attachment loop for tethering keys or a second leash. Covers the terrain hazards (other dogs, wildlife, dim light) without weighing you down.",
    belt: '2"',
    beltNote:
      "A 2\" duty belt distributes weight better on long days and keeps the loadout from bouncing on technical terrain.",
    beltProduct: {
      name: 'IDOGEAR SPORTS Tactical 2" Heavy-Duty MOLLE Belt',
      url: "https://www.amazon.com/dp/B0G2PTBGF2",
      costCents: 3000,
    },
    modules: [
      { slug: "first-aid-kit-mount", plate: "plates/kanix_plate_3x3_52x6.5.stl", angle: 135, note: "Hours from a trailhead — first aid is non-negotiable." },
      { slug: "waste-bag-dispenser", plate: "plates/kanix_plate_3x3_52x6.5.stl", angle: -45 },
      { slug: "mk3-canister-holder", plate: "plates/kanix_plate_3x3_52x6.5.stl", angle: -90, note: "Off-leash dog encounters are most likely on shared trails." },
      { slug: "flashlight-holster-c3", plate: "plates/kanix_plate_3x3_52x6.5.stl", angle: 90, note: "Dawn starts and dusk returns — bring real light." },
      { slug: "carabiner-clip", plate: "plates/kanix_plate_3x3_52x6.5.stl", variant: "tiny", angle: 30, note: "Tether keys, a multitool, or a second leash." },
    ],
  },
  {
    slug: "trainer",
    name: "The Trainer",
    tagline: "A purpose-built marker-training rig for handlers running real reward-based programs.",
    description:
      "Five Kanix™ modules on a 1.5\" duty belt for people who train every day and are done improvising — pros doing 1:1 marker sessions, sport handlers prepping for trials, and dedicated owners working through structured plans with a real instructor. Clicker and Wilderdog treat pouch sit dominant-hand for sub-second reinforcement; waste bags, a dump pouch for the catch-all stuff, and a pair of attachment loops stay out of the way until you reach for them. A setup that stays put session after session instead of sliding around a soft training belt.",
    belt: '1.5"',
    beltNote:
      "A 1.5\" duty belt is plenty for a training loadout and tucks under everyday clothing better than a 2\" belt.",
    beltProduct: {
      name: "IDOGEAR SPORTS Tactical Ratchet Belt (1.5\")",
      url: "https://www.amazon.com/dp/B0FJDMN78R",
      costCents: 2500,
    },
    modules: [
      { slug: "clicker-holder", plate: "plates/kanix_plate_3x2_38x5.3.stl", angle: 30, note: "Clicker on a 3×2 plate, dominant-hand side for fast marker work." },
      { slug: "treat-bag-mount", plate: "plates/kanix_plate_3x2_38x5.3.stl", angle: 75, note: "Wilderdog treat pouch — fastest possible reinforcement." },
      { slug: "waste-bag-dispenser", plate: "plates/kanix_plate_3x2_38x5.3.stl", angle: -90 },
      { slug: "dump-bag-mount", plate: "plates/kanix_plate_3x2_38x5.3.stl", angle: -45, note: "Catch-all storage — backup leash, wipes, treats refill, whatever else you pick up on a session." },
      { slug: "carabiner-clip", plate: "plates/kanix_plate_3x2_38x5.3.stl", variant: ["small", "small"], angle: 130, note: "Two of the larger 1×2 attachment loops on one 3×2 plate — clip a second leash, water bottle, or anything that needs more than a tiny loop." },
    ],
  },
  {
    slug: "pro",
    name: "The Pro",
    tagline: "Everything The Trainer and The Walker carry, plus an e-collar and dump bag.",
    description:
      "Seven Kanix™ modules on a 1.5\" duty belt plus a hands-free BioThane heel lead — the lead loops directly onto the belt so both hands stay free for marker work, e-collar timing, and gear. Every Kanix™ module from The Trainer and The Walker, plus an e-collar holster for whichever receiver you run and a dump bag for the catch-all stuff. Clicker, treat pouch, e-collar, waste bags, C3 flashlight, dump bag, and two small attachment loops — one stacked on the clicker's 2×2 plate, one stacked on the C3's 2×2 plate, both filling the leftover 1×2 row. All on 3×2 38mm plates. You don't have to wear them all every day: each Kanix™ module is a hinged belt clip that snaps on and off in seconds without tools, so a Trainer-day kit becomes a Walker-day kit on the way out the door.",
    belt: '1.5"',
    beltNote:
      "A 1.5\" duty belt keeps the loadout compact even with the full Pro kit, and tucks under everyday clothing better than a 2\" belt.",
    beltProduct: {
      name: "IDOGEAR SPORTS Tactical Ratchet Belt (1.5\")",
      url: "https://www.amazon.com/dp/B0FJDMN78R",
      costCents: 2500,
    },
    modules: [
      { slug: "clicker-holder", plate: "plates/kanix_plate_3x2_38x5.3.stl", variant: "38mm", angle: 22.5, note: "Clicker on the 38mm 2×2 variant of a 3×2 plate, dominant-hand side for fast marker work. Shares its 3×2 plate with a small attachment loop." },
      { slug: "carabiner-clip", plate: "plates/kanix_plate_3x2_38x5.3.stl", variant: "small", angle: 22.5, note: "Small attachment loop stacked on the clicker's plate — clip a second leash, water bottle, or anything that needs more than a tiny loop." },
      { slug: "treat-bag-mount", plate: "plates/kanix_plate_3x2_38x5.3.stl", angle: 45, note: "Wilderdog treat pouch — fastest possible reinforcement." },
      {
        groupLabel: "E-Collar Holster",
        groupDescription:
          "Pick the holster that matches the e-collar receiver you already own. On a 1.5\" duty belt the holster's 3×3 hole pattern mounts to a 3×2 plate — the top row of holes is unused.",
        choices: ["mini-educator-holder", "dogtra-200ncpt-202c-arc-holder", "dogtra-280x-arcx-holder"],
        plate: "plates/kanix_plate_3x2_38x5.3.stl",
        angle: 67.5,
        note: "Pick the holster that matches the e-collar receiver you already own.",
      },
      { slug: "waste-bag-dispenser", plate: "plates/kanix_plate_3x2_38x5.3.stl", angle: 90 },
      { slug: "dump-bag-mount", plate: "plates/kanix_plate_3x2_38x5.3.stl", angle: -157.5, note: "Catch-all storage — backup leashes, wipes, extras you pick up on a session." },
      { slug: "quick-detach-biothane-heel-lead", angle: -146.25, note: "BioThane lead, used as a heel/slip lead. Loops directly around the belt — no plate." },
      { slug: "flashlight-holster-c3", plate: "plates/kanix_plate_3x2_38x5.3.stl", variant: "38mm", angle: -135, note: "Wuben C3 (38mm 2×2 variant) shares its 3×2 plate with a small attachment loop for clipping keys or a phone tether." },
      { slug: "carabiner-clip", plate: "plates/kanix_plate_3x2_38x5.3.stl", variant: "small", angle: -135, note: "Small attachment loop stacked on the C3's plate — clip your own carabiner, snap hook, or D-clip to it." },
    ],
  },
];

// One resolved entry. Either a single module (kind === "module" |
// "coming-soon") or a "pick one of" group of modules (kind === "group").
export type ResolvedLoadoutModule =
  | {
      kind: "module" | "coming-soon";
      module: Module | ComingSoonModule;
      plate?: string;
      variant?: string | string[];
      note?: string;
      angle?: number;
    }
  | {
      kind: "group";
      groupLabel: string;
      groupDescription?: string;
      // Each candidate the user picks among. `mod` is the module record;
      // `kind` distinguishes shipping vs coming-soon for the page link.
      candidates: Array<{ kind: "module" | "coming-soon"; module: Module | ComingSoonModule }>;
      plate?: string;
      note?: string;
      angle?: number;
    };

// Helper: resolve each entry. For a normal entry, look up the slug in
// modules (then comingSoonModules). For a "pick one of" group, resolve
// every candidate slug. Logs a warning if any slug doesn't resolve.
export function resolveLoadout(loadout: Loadout): ResolvedLoadoutModule[] {
  return loadout.modules
    .map((entry): ResolvedLoadoutModule | null => {
      if (entry.choices && entry.choices.length > 0) {
        const candidates = entry.choices
          .map((slug) => {
            const mod = modules.find((m) => m.slug === slug);
            if (mod) return { kind: "module" as const, module: mod };
            const cs = comingSoonModules.find((m) => m.slug === slug);
            if (cs) return { kind: "coming-soon" as const, module: cs };
            console.warn(
              `[loadouts] loadout "${loadout.slug}" group references unknown slug "${slug}"`,
            );
            return null;
          })
          .filter((x): x is { kind: "module" | "coming-soon"; module: Module | ComingSoonModule } => x !== null);
        if (candidates.length === 0) return null;
        return {
          kind: "group",
          groupLabel: entry.groupLabel ?? "Pick one",
          groupDescription: entry.groupDescription,
          candidates,
          plate: entry.plate,
          note: entry.note,
          angle: entry.angle,
        };
      }
      if (!entry.slug) return null;
      const mod = modules.find((m) => m.slug === entry.slug);
      if (mod) {
        return { kind: "module", module: mod, plate: entry.plate, variant: entry.variant, note: entry.note, angle: entry.angle };
      }
      const cs = comingSoonModules.find((m) => m.slug === entry.slug);
      if (cs) {
        return { kind: "coming-soon", module: cs, plate: entry.plate, variant: entry.variant, note: entry.note, angle: entry.angle };
      }
      console.warn(
        `[loadouts] loadout "${loadout.slug}" references unknown module slug "${entry.slug}"`,
      );
      return null;
    })
    .filter((x): x is ResolvedLoadoutModule => x !== null);
}

// One row in the loadout's print list. `kind` tells the page how to label
// it ("Mount" — the plate or belt clip everything bolts to — vs "Module"
// — the accessory itself); `stl` is the path under public/models/.
export interface LoadoutPrintItem {
  kind: "mount" | "module";
  stl: string;
  count: number;
  label: string;
}

// Helper: collect everything the user needs to print for this loadout —
// the unique mounts (plates or belt clips) AND each module's default STL.
// Modules with `noModel: true` (e.g. the BioThane heel lead) are skipped.
// Mounts come first so they print before the accessories that bolt to them.
export function summarizeLoadoutPrintList(loadout: Loadout): LoadoutPrintItem[] {
  // Mounts first. Skip entries with no plate (e.g. the BioThane heel lead —
  // it loops around the belt on its own). "Pick one of" group entries
  // still contribute their plate (the user prints one mount even if they
  // pick one of N holsters).
  const mountCounts = new Map<string, number>();
  for (const entry of loadout.modules) {
    if (!entry.plate) continue;
    mountCounts.set(entry.plate, (mountCounts.get(entry.plate) ?? 0) + 1);
  }
  const mounts: LoadoutPrintItem[] = [...mountCounts.entries()].map(
    ([stl, count]) => ({
      kind: "mount",
      stl,
      count,
      label: plateLabel(stl),
    }),
  );

  // Modules next. For modules with `genericVariants`, use the variant id
  // from the loadout entry to look up the correct STL/label; otherwise use
  // the module's default `stlFile`. Skip modules that don't have a model
  // (noModel) or that aren't in the printable modules list (coming-soon).
  // Skip "pick one of" groups — the user prints one of them, but we don't
  // know which, so the group surfaces in the products section instead.
  // Multi-variant entries (`variant: string[]`) add one STL per variant.
  const moduleCounts = new Map<string, { count: number; name: string }>();
  const addModuleSTL = (stl: string, label: string) => {
    const existing = moduleCounts.get(stl);
    moduleCounts.set(
      stl,
      existing
        ? { count: existing.count + 1, name: label }
        : { count: 1, name: label },
    );
  };
  for (const entry of loadout.modules) {
    if (entry.choices) continue;
    const mod = modules.find((m) => m.slug === entry.slug);
    if (!mod || mod.noModel) continue;

    const variantIds: Array<string | undefined> = Array.isArray(entry.variant)
      ? entry.variant
      : [entry.variant];

    for (const vid of variantIds) {
      let stl: string | undefined;
      let label: string = mod.name;
      if (vid && mod.genericVariants) {
        const opt = mod.genericVariants.groups
          .flatMap((g) => g.options)
          .find((o) => o.id === vid);
        if (opt) {
          stl = opt.stlFile;
          label = `${mod.name} — ${opt.label}${opt.sublabel ? ` (${opt.sublabel})` : ""}`;
        }
      }
      if (!stl) stl = mod.stlFile;
      if (!stl) continue;
      addModuleSTL(stl, label);
    }
  }
  const modulesList: LoadoutPrintItem[] = [...moduleCounts.entries()].map(
    ([stl, { count, name }]) => ({
      kind: "module",
      stl,
      count,
      label: name,
    }),
  );

  return [...mounts, ...modulesList];
}

// Helper: total M5×10 button-head cap screws a loadout needs across all
// of its modules. Modules without a declared `screwCount` are skipped
// (treated as unknown, not zero). For "pick one of" groups, take the
// max screw count across candidates so the user has enough no matter
// which they pick.
export function totalLoadoutScrews(loadout: Loadout): number {
  let total = 0;
  for (const entry of loadout.modules) {
    if (entry.choices && entry.choices.length > 0) {
      let groupMax = 0;
      for (const slug of entry.choices) {
        const mod =
          modules.find((m) => m.slug === slug) ??
          comingSoonModules.find((m) => m.slug === slug);
        if (mod && typeof mod.screwCount === "number") {
          groupMax = Math.max(groupMax, mod.screwCount);
        }
      }
      total += groupMax;
      continue;
    }
    if (!entry.slug) continue;
    const mod =
      modules.find((m) => m.slug === entry.slug) ??
      comingSoonModules.find((m) => m.slug === entry.slug);
    if (mod && typeof mod.screwCount === "number") {
      // Multi-variant entries (e.g. two carabiner clips on one plate) need
      // screws for each clip — multiply by the variant count.
      const multiplier = Array.isArray(entry.variant) ? entry.variant.length : 1;
      total += mod.screwCount * multiplier;
    }
  }
  return total;
}

// One row in the "Products for this loadout" section. `source` is either
// the loadout itself (for the belt) or the slug of the module the product
// belongs to (so the page can link back). `required` is true if the
// product is mandatory to use the loadout (the belt is always required;
// a module's `required: true` product is also required); otherwise the
// product is just a suggestion. `pickOneGroup` is set when the product
// belongs to a "pick one of" cluster (e.g. e-collar receivers) — the
// page draws a heading and groups all rows with the same value.
export interface LoadoutProductRow {
  name: string;
  url: string;
  required: boolean;
  source: { kind: "belt" } | { kind: "module"; slug: string; moduleName: string };
  pickOneGroup?: string;
}

// Helper: collect every product the user might want to buy for this
// loadout. The belt is first (if specified), then every module's products
// in module-list order. "Pick one of" group entries surface every
// candidate module's products with the same `pickOneGroup` tag so the
// page can render them as a single cluster.
export function collectLoadoutProducts(loadout: Loadout): LoadoutProductRow[] {
  const rows: LoadoutProductRow[] = [];

  if (loadout.beltProduct) {
    rows.push({
      name: loadout.beltProduct.name,
      url: loadout.beltProduct.url,
      required: true,
      source: { kind: "belt" },
    });
  }

  for (const entry of loadout.modules) {
    if (entry.choices && entry.choices.length > 0) {
      const groupLabel = entry.groupLabel ?? "Pick one";
      for (const slug of entry.choices) {
        const mod =
          modules.find((m) => m.slug === slug) ??
          comingSoonModules.find((m) => m.slug === slug);
        if (!mod || !mod.products) continue;
        for (const p of mod.products) {
          rows.push({
            name: p.name,
            url: p.url,
            // Products inside a pick-one cluster are "pick one of" — none
            // is individually required (the cluster as a whole is). We
            // mark them as not required individually; the page renders a
            // group header noting one must be chosen.
            required: false,
            source: { kind: "module", slug: mod.slug, moduleName: mod.name },
            pickOneGroup: groupLabel,
          });
        }
      }
      continue;
    }
    const mod =
      modules.find((m) => m.slug === entry.slug) ??
      comingSoonModules.find((m) => m.slug === entry.slug);
    if (!mod || !mod.products) continue;
    for (const p of mod.products) {
      rows.push({
        name: p.name,
        url: p.url,
        required: p.required === true,
        source: { kind: "module", slug: mod.slug, moduleName: mod.name },
      });
    }
  }

  return rows;
}

// Parse the STL filename into a human label. Filenames follow two patterns
// that the rest of the codebase already establishes:
//   - "plates/kanix_plate_<grid>_<belt>x<thickness>.stl"
//   - "belt_clip_<grid>_<belt>mm.stl"
// Anything that doesn't match falls through to a sensible default so a typo
// in loadouts.md doesn't crash the page — but the value will read wrong, so
// the user notices.
export function plateLabel(plate: string | undefined | null): string {
  if (!plate) return "(no plate specified)";
  const plateMatch = plate.match(/kanix_plate_(\d+x\d+)_(\d+)x([\d.]+)\.stl$/);
  if (plateMatch) {
    const [, grid, belt, thickness] = plateMatch;
    return `Kanix™ Plate — ${grid} grid, ${belt}mm belt, ${thickness}mm thick`;
  }
  const clipMatch = plate.match(/belt_clip_(\d+x\d+)_(\d+)mm\.stl$/);
  if (clipMatch) {
    const [, grid, belt] = clipMatch;
    return `Belt Clip — ${grid} grid, ${belt}mm belt`;
  }
  return plate;
}

// ─── Kit pricing ─────────────────────────────────────────────────────────
//
// Sell-price calculation for a loadout sold as a complete, pre-assembled
// kit. Data only — not surfaced in the UI yet. Sums:
//
//   - One `kitModulePriceCents` per kit-eligible loadout entry (the
//     module is hand-priced, e.g. $35 for a typical plate-and-module
//     line, $50 for the BioThane heel lead). The carabiner-clip line
//     covers a plate plus up to two clips of any size for one price.
//   - For every `required: true` product on each module, `costCents`
//     marked up by `accessoryMarkup` (default 1.10).
//   - The belt at `beltProduct.costCents × accessoryMarkup`.
//
// Modules with no `kitModulePriceCents` contribute nothing and are
// flagged in `LoadoutPriceBreakdown.missingModuleSlugs` so the caller
// can decide whether the kit is sellable yet.

export interface LoadoutPriceBreakdown {
  // Sum of every kit-eligible module line (flat sell prices).
  moduleCents: number;
  // Sum of every required product's marked-up cost.
  accessoriesCents: number;
  // Belt cost × markup.
  beltCents: number;
  // moduleCents + accessoriesCents + beltCents.
  totalCents: number;
  // Slugs of modules that are part of this loadout but have no
  // kitModulePriceCents yet. If non-empty, the kit isn't fully priced.
  missingModuleSlugs: string[];
  // Names of required products that are missing costCents. If non-empty,
  // the accessory total under-counts.
  missingProductNames: string[];
}

export interface PriceLoadoutOptions {
  // Markup applied to purchased accessories and the belt. Default 1.10.
  accessoryMarkup?: number;
}

export function priceLoadout(
  loadout: Loadout,
  options: PriceLoadoutOptions = {},
): LoadoutPriceBreakdown {
  const accessoryMarkup = options.accessoryMarkup ?? 1.1;
  let moduleCents = 0;
  let accessoriesCents = 0;
  const missingModuleSlugs: string[] = [];
  const missingProductNames: string[] = [];

  // For "pick one of" groups, use the first candidate's pricing data —
  // every candidate in a group is the same size of plate-with-holster,
  // and the kit doesn't bundle the receiver itself, so the price is the
  // same regardless of choice.
  for (const resolved of resolveLoadout(loadout)) {
    const mod =
      resolved.kind === "group" ? resolved.candidates[0]?.module : resolved.module;
    if (!mod) continue;

    const kitPrice = (mod as Module).kitModulePriceCents;
    if (kitPrice === undefined) {
      missingModuleSlugs.push(mod.slug);
    } else {
      moduleCents += kitPrice;
    }

    for (const product of mod.products ?? []) {
      if (!product.required) continue;
      if (product.costCents === undefined) {
        missingProductNames.push(product.name);
        continue;
      }
      accessoriesCents += Math.round(product.costCents * accessoryMarkup);
    }
  }

  let beltCents = 0;
  if (loadout.beltProduct?.costCents !== undefined) {
    beltCents = Math.round(loadout.beltProduct.costCents * accessoryMarkup);
  } else if (loadout.beltProduct) {
    missingProductNames.push(loadout.beltProduct.name);
  }

  return {
    moduleCents,
    accessoriesCents,
    beltCents,
    totalCents: moduleCents + accessoriesCents + beltCents,
    missingModuleSlugs,
    missingProductNames,
  };
}
