#!/usr/bin/env bash
# Sync PUBLIC_* variables from root .env into site/.env.
# Astro only exposes PUBLIC_-prefixed variables to the browser, so the site
# only needs those — never secrets. Run automatically via site's predev/prebuild.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$ROOT_DIR/.env"
DST="$ROOT_DIR/site/.env"

if [ ! -f "$SRC" ]; then
  echo "sync-env: $SRC not found; skipping" >&2
  exit 0
fi

{
  echo "# Auto-generated by scripts/sync-env.sh — do not edit."
  echo "# Source: $SRC"
  grep -E '^PUBLIC_[A-Z0-9_]+=' "$SRC" || true
} > "$DST"

echo "sync-env: wrote $DST"
